services:
  elasticsearch:
    image: elasticsearch:8.6.1
    container_name: es
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      xpack.security.enabled: false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:9200/_cluster/health || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elastic

  logstash:
    image: logstash:8.6.1
    container_name: ls
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/pipelines.yml
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    command: logstash --config.reload.automatic

  kibana:
    image: kibana:8.6.1
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
    image: elastic/filebeat:8.6.2
    container_name: fb
    depends_on:
      - logstash
    networks:
      - elastic
    user: root
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - ./sample_logs/:/usr/share/filebeat/sample_logs
      - ./filebeat/inputs/:/usr/share/filebeat/config/inputs/
    command: [-c, /usr/share/filebeat/filebeat.yml, --strict.perms=false, -e]
networks:
  elastic:
    driver: bridge

configs:
  filebeat_config:
    file: ./filebeat/filebeat.yml
  logstash_config:
    file: ./logstash/pipelines.yml
